### ISSUE TITLE
Cross module test resources not found

### ISSUE THREAD

**Issue by zt64** [goncalossilva/kotlinx-resources#131]
Hi, in my project I have a common `testing` module that all my other modules depend upon in their commonTest sourceset. `testing` uses kotlinx-resources for a resource wrapper object. The issue is though when I use a resource from outside the testing module it's unable to find the file. 

testing - commonMain
```
object TestResources {
    val RESOURCE_1 = Resource("src/commonMain/resources/video/SampleVideo_1280x720_5mb.mp4")
}
```
lib - commonTest
```
TestResources.RESOURCE_1.readBytes()
```
`src/commonMain/resources/video/SampleVideo_1280x720_5mb.mp4: No such file or directory`

And if I add the file to the same path in the current module then it fixes it. Is this something with the library that can be fixed?

**Comment by goncalossilva** [comment]
Resource path is relative to the project under compilation ([ref](https://github.com/goncalossilva/kotlinx-resources/blob/4d961bd97907ab527de60024cbe08557af246118/resources-plugin/src/main/kotlin/ResourcesPlugin.kt#L122-L130)). There is no support for exporting or consuming resources alongside other projects, and I'm not sure that this would be easy to do in the way the plugin currently works, unfortunately.

It's possible you can still bundle this in your testing module and rely on the relative path to other modules being the same every time. E.g., `Resource("../testing/src/commonMain/resources/video/SampleVideo_1280x720_5mb.mp4")`. It's not pretty, but it should work, provided the relative path from `testing` to other modules is the same every time.
