### ISSUE TITLE
Does this work with commonMain?

### ISSUE THREAD

**Issue by mikeholler** [goncalossilva/kotlinx-resources#20]
The README shows this snippet with commonTest, but I have a use-case for commonMain. Is it expected that this library will work there, too?

```
kotlin {
    sourceSets {
        val commonTest by getting {
            dependencies {
                implementation("com.goncalossilva:resources:<version>")
            }
        }
    }
}
```

**Comment by mikeholler** [comment]
What I want to do:

```
kotlin {
    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("com.goncalossilva:resources:<version>")
            }
        }
    }
}
```

**Comment by goncalossilva** [comment]
No. The plugin [only works with test resources](https://github.com/goncalossilva/kotlinx-resources/blob/605568e5a394a78e41fc44f5c3c1443d461c2c71/resources-plugin/src/main/kotlin/ResourcesPlugin.kt#L87-L88). There are some reasons for this, such as resources not being packaged with binaries in most cases, or Karma only being available in testing.

What is your use case?

**Comment by goncalossilva** [comment]
Closing for now, but happy to discuss if there's follow-up. :)

**Comment by KevinnZou** [comment]
> No. The plugin [only works with test resources](https://github.com/goncalossilva/kotlinx-resources/blob/605568e5a394a78e41fc44f5c3c1443d461c2c71/resources-plugin/src/main/kotlin/ResourcesPlugin.kt#L87-L88). There are some reasons for this, such as resources not being packaged with binaries in most cases, or Karma only being available in testing.
> 
> What is your use case?

I have a use case in which I need to read an HTML file in CommonMain and load it by WebView on each platform. Does this library support reading resources under the commonMain folder?

**Comment by goncalossilva** [comment]
It does not. I'm afraid the way resources are made available to some platforms is not suitable for any environment that's not a test environment. For example, it leverages Karma in JS, which is the test runner. It also leverages resources in JVM platforms, which includes Android, where they are discouraged.

Theoretically, it could be made to work in `commonMain` once #36 is done and if we exclude JS, although I feel that starts to deviate from the intended scope of the library.

It's not a scalable solution, but for a single HTML file, consider inlining it in a multi-line string. You can even automate generating that Kotlin file based on the original HTML file at build time.

**Comment by KevinnZou** [comment]
> It's not a scalable solution, but for a single HTML file, consider inlining it in a multi-line string. You can even automate generating that Kotlin file based on the original HTML file at build time.

Thanks for your instruction! Could you provide more information on how to generate a Kotlin file based on an HTML file at build time?

**Comment by goncalossilva** [comment]
You can create a Gradle task that, during build time, reads the file, and uses it to generate a Kotlin file. I'm sure you'll find some examples online!
