### ISSUE TITLE
Read binary data

### ISSUE THREAD

**Issue by Burtan** [goncalossilva/kotlinx-resources#39]
Currently Resources can only be read as text. What about binary data, e.g. image data?

**Comment by goncalossilva** [comment]
On paper, we may be able to read files as bytes across platforms and have a new `readBytes` method.

For JVM, there's `File.readBytes()`. For POSIX, there's an `"rb"` mode for `fopen`. For Node, `fs.readFileSync` appears to support a binary mode(?). For JS, `XMLHttpRequest` supports `ArrayBuffer` responses which we may be able to cast safely. For Apple platforms, I have no idea.

But this requires proper exploration on the best way to do it in each platform.

**Comment by Burtan** [comment]
Thanks for the answer, doesn't seem trivial. I'll go for base64 text files until this feature might be added.

**Comment by goncalossilva** [comment]
An initial version of this is done and released on 0.3.0. Give it a try and let me know what you think. :)

**Comment by krisbitney** [comment]
Amazing. Works perfectly for me. Thanks!!

**Comment by goncalossilva** [comment]
Happy to hear. Thanks for testing!
