### ISSUE TITLE
Gradle plugin clashes with moko-resources on mac

### ISSUE THREAD

**Issue by Burtan** [goncalossilva/kotlinx-resources#51]
Hey,

on mac the gradle plugin generates the following tasks.

```
   > Cannot add task 'copyResourcesDebugTestIosX64' as a task with that name already exists.
   > Cannot add task 'copyResourcesDebugTestIosArm64' as a task with that name already exists.
   > Cannot add task 'copyResourcesDebugTestIosSimulatorArm64' as a task with that name already exists.
```

Unfortunately the gradle plugin from the widely used [moko-resources project ](https://github.com/icerockdev/moko-resources)creates the same tasks.

I think you should rename them. 
Thanks :-)

**Comment by goncalossilva** [comment]
Hey, thanks for bringing this to my attention!

I was inclined to fix this by renaming the task, but while struggling to come up with another appropriate name (all it does is really copy resources…), I wondered why one would use `kotlinx-resources` _and_ `moko-resources`. The former is much simpler and lightweight, specifically built to trivialize testing with files in KMP. The latter has 10x more features and is 10x bigger, aimed at production use. In theory, one can [mostly replace this library with moko](https://github.com/icerockdev/moko-resources#example-10---plain-file-resource-access) (if willing to bring in all the other features, that is). As a result, I'm not sure about renaming. For those already using moko, my advice would be to use it for loading test resources as well.

**Comment by Burtan** [comment]
I'll think about it :D. I used this plugin for testing code that needs image data and moko-resources just for i18n.

**Comment by goncalossilva** [comment]
Give it a try. I suspect you won't need this library. If you do find a use case for kotlinx-resources that moko-resources doesn't cover, let me know and I'll address it.

**Comment by Burtan** [comment]
https://github.com/icerockdev/moko-resources/issues/193

moko-resources currently does not support shared test resources.

**Comment by goncalossilva** [comment]
Thanks for checking—this is now fixed. :)

**Comment by goncalossilva** [comment]
Huh, yes. Thanks for flagging. This is **much** worse. It's an official plugin. 🤦 I'm reverting the previous change.

For now, `kotlinx-resources` will be incompatible with `moko-resources` for the moment. It's very likely there is a workaround, such as only applying `moko-resources` when _not_ in testing, and applying `kotlinx-resources` only in testing, but I haven't tested any particular approach.
