### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by DRSchlaubi** [goncalossilva/kotlinx-resources#55]
I created a minimal project, where all tests faill because of a FileNotFoundException

project: https://github.com/DRSchlaubi/kotlinx-resources-test

**Comment by goncalossilva** [comment]
You need to include the path from the project's directory, as explained in
the README. Give it a try.

**Comment by DRSchlaubi** [comment]
Oh, sounds like I misunderstood the README, I thought the files must be accessible from a path relative to the project thx

**Comment by goncalossilva** [comment]
Good to hear! I'll work up make that clearer. 🙂
