### ISSUE TITLE
Provide helper in Gradle Plugin, so I can keep the plugin and dependency in sync

### ISSUE THREAD

**Issue by aSemy** [goncalossilva/kotlinx-resources#63]
Hi 👋 

At the moment I have to set the version of kotlinx-resources twice. First in the `plugins {}` block, and next in the dependencies.

```kotlin
// build.gradle.kts

plugins {
    id("com.goncalossilva.resources") version "<version>"
}

kotlin {
    sourceSets {
        val commonTest by getting {
            dependencies {
                implementation("com.goncalossilva:resources:<version>")
            }
        }
    }
}
```

I would like for the Gradle plugin to provide a utility so that it can declare the version of kotlinx-resources. 

---

I have two suggestions:

1. Generate a Kotlin file in the kotlinx-resources Gradle Plugin subproject that contains the project version.
    
    
    ```kotlin
    // ./resources-plugin/build/generated/src/kotlin/ResourcesProperties.kt
    
    package com.goncalossilva.resources
    
    object ResourcesProperties {
      const val KOTLINX_RESOURCES_VERSION = "<version>"
    }
    ```
    
    And then, in one way or another, I can import this variable in my build script.
    
    ```kotlin
    // build.gradle.kts
    
    import com.goncalossilva.resources.KOTLINX_RESOURCES_VERSION
    
    plugins {
        id("com.goncalossilva.resources") version "<version>"
    }
    
    kotlin {
        sourceSets {
            val commonTest by getting {
                dependencies {
                    implementation("com.goncalossilva:resources:$KOTLINX_RESOURCES_VERSION")
                }
            }
        }
    }
    ```

2. A further improvement would be for the `com.goncalossilva.resources` plugin to automatically add the dependency to `commonTest`. It can do this by [reacting](https://docs.gradle.org/8.1.1/userguide/implementing_gradle_plugins.html#reacting_to_plugins) to the Kotlin/Multiplatform plugin and automatically adding a dependency.

Of course keeping the version in sync is also possible using [`libs.versions.toml`](https://docs.gradle.org/8.1.1/userguide/platforms.html#sub:conventional-dependencies-toml), but option 2 would be very convenient!

**Comment by aSemy** [comment]
Ooh it's already in there!

So I can do this:

```kotlin
// build.gradle.kts

import com.goncalossilva.resources.BuildConfig.VERSION as KotlinxResourcesVersion

plugins {
    id("com.goncalossilva.resources") version "<version>"
}

kotlin {
    sourceSets {
        val commonTest by getting {
            dependencies {
                implementation("com.goncalossilva:resources:$KotlinxResourcesVersion")
            }
        }
    }
}
```

It would be nice if this was added to the README.


It would also be nice if the version had a more distinctive name. At the moment I think referencing `BuildConfig.VERSION` is too vague. I can use an import alias to make it more clear, but it would be nice if I didn't have to.

**Comment by goncalossilva** [comment]
Hey! Thanks for the suggestion and for taking the time to explore a couple of options.

The whole ecosystem is moving towards version catalogs, so I'm reluctant to add functionality that's particular to this library. Using an import alias works, but even that relies on `BuildConfig`, which is really meant for internal usage, hence not something I'd be keen to document in the README as it may very well change in the future.

I'll keep thinking about this, but I'd advise leaning on version catalogs for the moment.

**Comment by goncalossilva** [comment]
> You might want to mark BuildConfig as internal, because at the moment it's publicly accessible.

Absolutely. It didn't occur to me that it would be exported, so I didn't check. See #67.

> Just to re-iterate, it would still be really convenient for the com.goncalossilva.resources Gradle plugin to automatically add the com.goncalossilva:resources dependency to commonTest, so that (as a plugin user) the configuration is as simple as possible, and I could be more confident that my configuration will remain updated. But of course I respect if that's not something you think the plugin should do.

In _theory_, one can use the plugin without the library, but more importantly, I'm not confident that I can easily guess/inject into all configurations people might use it in. E.g., one may only add it in a few specific configurations, not all (i.e., not `commonTest`). I will think more about this, it would certainly be convenient and prevent errors.

Do you happen to have an example of a plugin that does this?

**Comment by aSemy** [comment]
> Absolutely. It didn't occur to me that it would be exported, so I didn't check. See #67.

👍 

> In _theory_, one can use the plugin without the library, but more importantly, I'm not confident that I can easily guess/inject into all configurations people might use it in. E.g., one may only add it in a few specific configurations, not all (i.e., not `commonTest`). I will think more about this, it would certainly be convenient and prevent errors.
> 
> Do you happen to have an example of a plugin that does this?

I haven't published a Gradle plugin automatically adds dependencies to Configurations of another plugin, but I have made plugins ([Dokkatoo](https://github.com/adamko-dev/dokkatoo/) and [BCV MU](https://github.com/adamko-dev/kotlin-binary-compatibility-validator-mu/)) that automatically adds dependencies to their own Configurations (and the versions of these dependencies can even be [configured](https://github.com/adamko-dev/kotlin-binary-compatibility-validator-mu/blob/b96010adadbd9cb359898fd8a82dc396e86d1376/modules/bcv-gradle-plugin/src/main/kotlin/BCVProjectPlugin.kt#L45-L53) by users).


If you're asking for a practical demo, then I think this is most basic way to add the dependency automatically:

```kotlin
project.pluginManager.withPlugin("org.jetbrains.kotlin.multiplatform") {
    project.dependencies.add(
        "commonTestImplementation",
        "com.goncalossilva:resources:${BuildConfig.VERSION}",
    )
}
```

Yes, it's stringly-typed, but `commonTestImplementation` is pretty baked into KGP, and unlikely to change, and using the string means you don't have to add a dependency on Kotlin Gradle Plugin, which would require adding it as a compileOnly dependency and risk getting the class usages out of sync with the runtime version added by users. 

Users would be able to override the dependency too, by setting it manually (I'm 90% sure of that, anyway!).

Yes, it's possible users might add additional source sets/configurations that don't extend from commonTest, and therefore won't pick up the `com.goncalossilva:resources` dependency automatically. I suspect that's a rare case though. And if users are configuring a script like that then (hopefully) they're comfortable enough with Gradle to figure out that a manual dependency is required.

Anyway, I think you're right to take some time to think it over. There's no definite right answer!
