### ISSUE TITLE
Kotlin 1.9.0 compatibility

### ISSUE THREAD

**Issue by StefanOltmann** [goncalossilva/kotlinx-resources#74]
Please update the lib to work with Kotlin 1.9.0

`Resource("myresource").readText()` throws an `com.goncalossilva.resources.FileReadException` on `macosArm64` and `iosSimulatorArm64`. JVM is not affected.

The same code works fine for Kotlin 1.8.20

**Comment by goncalossilva** [comment]
Thanks for flagging, @StefanOltmann! I've been OOO, but it's on my list.

**Comment by goncalossilva** [comment]
Version v0.4.0 with support for Kotlin 1.9.0 is out. Thank you for your patience!
